# Generated by Django 5.2.5 on 2025-11-06 18:34

import django.core.validators
import django.db.models.deletion
import profiles.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=30, validators=[django.core.validators.RegexValidator('^[0-9+\\-\\s()\\.]+$', 'Formato de teléfono inválido.')])),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('localidad', models.CharField(blank=True, max_length=120)),
                ('datos_personales', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to=profiles.models.profile_photo_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
