# Generated by Django 5.2.5 on 2025-09-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='img/placeholder.png', null=True, upload_to='img/products/'),
        ),
    ]
