# Generated by Django 5.2.5 on 2025-10-06 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_product_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stovk',
            field=models.CharField(blank=True, default='1', max_length=3),
        ),
    ]
