# Generated by Django 5.2.5 on 2025-10-06 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_product_stovk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stovk',
            new_name='stock',
        ),
    ]
