# Generated by Django 5.2.5 on 2025-10-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_rename_stovk_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, default='1', max_length=3),
        ),
    ]
