# Generated by Django 5.2.5 on 2025-10-22 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='query',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='source',
            field=models.CharField(blank=True, default='Coto', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
