# Generated by Django 5.2.5 on 2025-11-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_product_query_product_source_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.TextField(blank=True, default='Varios', max_length=50),
        ),
    ]
