# Generated by Django 5.2.5 on 2025-11-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_productevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productevent',
            name='event_type',
            field=models.CharField(choices=[('cart_add', 'Agregado al carrito'), ('cart_remove', 'Quitado del carrito'), ('purchase', 'Compra')], max_length=20),
        ),
    ]
