# Generated by Django 5.2.5 on 2025-11-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_alter_productevent_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productnotification',
            name='type',
            field=models.CharField(choices=[('cart', 'Agregado al carrito'), ('cart_remove', 'Quitado del carrito'), ('purchase', 'Compra realizada')], max_length=20),
        ),
    ]
