# Generated by Django 5.2.5 on 2025-11-25 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_alter_productnotification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
